### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "librust.so" not found

### ISSUE THREAD

**Issue by digvijayu** [mozilla/rust-android-gradle#79]
I did the setup as mentioned in the README.md but I am getting below runtime error. Trying to replicate the same example as the samples in the project.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rc.rustandroidbuild, PID: 19094
    java.lang.UnsatisfiedLinkError: dlopen failed: library "librust.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.rc.rustandroidbuild.MainActivity.<init>(MainActivity.kt:10)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`
        
        
![image](https://user-images.githubusercontent.com/7867644/147710697-fca97bca-04c3-49ae-a0e4-d2ad63741ae8.png)

./app/build.gradle
```
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id("org.mozilla.rust-android-gradle.rust-android") version "0.9.0"
}

android {
    compileSdk 31

    defaultConfig {
        applicationId "com.rc.rustandroidbuild"
        minSdk 26
        targetSdk 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

apply plugin: 'org.mozilla.rust-android-gradle.rust-android'

cargo {
    module  = "../../rust"    
    libname = "rust"          
    targets = ["arm", "x86"] 
}

dependencies {

    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.4.0'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.2'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}

tasks.whenTaskAdded { task ->
    if ((task.name == 'javaPreCompileDebug' || task.name == 'javaPreCompileRelease')) {
        task.dependsOn 'cargoBuild'
    }
}
``` 

No sure what I might be missing. Any ideas? Thanks

**Comment by digvijayu** [comment]
I found the problem. When generated by cargo the `Cargo.toml` file does not have lib info. I added it and the app stopped crashing.

```
[lib]
name = "rust"
crate-type = ["staticlib", "cdylib"]
```
